[package]
name = "word-similarity"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.21.3"
redis = { version = "*", features = ["tokio-comp"] }
tokio = { version = "1.47.1", features = ["full"] }

